# These are supported funding model platforms

# github: chornthorn # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: chornthorn # Replace with a single Patreon username

