volumes:
  kc_data:
    name: keycloak-ext-data
services:
  keycloak:
    container_name: keycloak-ext-dev
    image: quay.io/keycloak/keycloak:26.0.0
    command: start-dev
    environment:
      DEBUG: "true"
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - kc_data:/opt/keycloak/data
      - ./target/*.jar:/opt/keycloak/providers/
    extra_hosts:
      - "host.docker.internal:host-gateway"
